# Generated by Django 2.2.14 on 2020-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hgjhgkjhgjk'),
    ]

    operations = [
        migrations.AddField(
            model_name='hgjhgkjhgjk',
            name='jhgjfhgjhgjhgfjh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
